---
- name: Set installation facts
  set_fact:
    phpstorm_installation_dir: '/opt/phpstorm-{{ phpstorm_version }}'

- name: 'Create folder'
  file:
    path: '{{ phpstorm_installation_dir }}'
    state: directory

- name: 'Download and extract phpstorm'
  shell: curl -sL {{ phpstorm_download_url }} | tar zx -C {{ phpstorm_installation_dir }} --strip-components 1
  args:
    creates: '{{ phpstorm_installation_dir }}/bin/phpstorm.sh'
  tags: ['skip_ansible_lint']

- name: 'Create symlink'
  file:
    src: '{{ phpstorm_installation_dir }}/bin/phpstorm.sh'
    dest: '/usr/local/bin/phpstorm'
    state: link
