---
- name: 'Create folder'
  file:
    path: '/opt/phpstorm'
    state: directory

- name: 'Download and extract phpstorm'
  command: curl -sL {{ phpstorm_download_url }} | tar zx -C /opt/phpstorm --strip-components 1
  args:
    creates: /opt/phpstorm/bin/phpstorm.sh


- name: 'Create symlink'
  file:
    src: '/opt/phpstorm/bin/phpstorm.sh'
    dest: '/usr/local/bin/phpstorm'
    state: link
